SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `closet-warehouse` DEFAULT CHARACTER SET latin1 ;
USE `closet-warehouse` ;

DROP TABLE IF EXISTS `closet-warehouse`.`category` ;

CREATE TABLE IF NOT EXISTS `closet-warehouse`.`category` (
  `CategoryID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `closet-warehouse`.`inventory` ;

CREATE TABLE IF NOT EXISTS `closet-warehouse`.`inventory` (
  `InventoryID` INT(11) NOT NULL AUTO_INCREMENT,
  `ProductID` INT(11) NULL DEFAULT NULL,
  `Quantity` INT(11) NULL DEFAULT NULL,
  `QuantityUnits` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`InventoryID`),
  INDEX `FK_INVENTORY_PRODUCT_idx` (`ProductID` ASC),
  CONSTRAINT `FK_INVENTORY_PRODUCT`
    FOREIGN KEY (`ProductID`)
    REFERENCES `closet-warehouse`.`products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `closet-warehouse`.`products` ;

CREATE TABLE IF NOT EXISTS `closet-warehouse`.`products` (
  `ProductID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NULL DEFAULT NULL,
  `Description` VARCHAR(2000) NULL DEFAULT NULL,
  `Brand` VARCHAR(45) NULL DEFAULT NULL,
  `CategoryID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `FK_PRODUCT_CATEGORY_idx` (`CategoryID` ASC),
  CONSTRAINT `FK_PRODUCT_CATEGORY`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `closet-warehouse`.`category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

